# Generated by Django 2.2 on 2019-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_links', '0002_notice_board_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board',
            name='branch',
            field=models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electronic Engineering', 'Electronic Engineering'), ('Industrial & Production Engineering', 'Industrial & Production Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Instrumentation and Control Engineering', 'Instrumentation and Control Engineering'), ('Applied Science and Humanity', 'Applied Science and Humanity'), ('Management', 'Management')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
