# Generated by Django 2.1.5 on 2019-02-25 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iert_news', '0007_new_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
