# Generated by Django 2.1.5 on 2019-02-26 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iert_news', '0013_auto_20190226_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
