# Generated by Django 2.1.5 on 2019-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to='document/')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='books_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to='document/')),
                ('info', models.TextField()),
            ],
        ),
    ]
