# Generated by Django 2.1.5 on 2019-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_degree_detail")]

    operations = [
        migrations.CreateModel(
            name="gallery_pic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
        )
    ]
