# Generated by Django 2.1.5 on 2019-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0011_auto_20190403_0452")]

    operations = [
        migrations.AlterField(
            model_name="degree_detail",
            name="branch_imformation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="degree_detail",
            name="branch_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="degree_detail",
            name="branch_vision",
            field=models.TextField(blank=True, null=True),
        ),
    ]
