# Generated by Django 2.2 on 2019-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0015_popup")]

    operations = [
        migrations.AlterField(model_name="popup", name="text", field=models.TextField())
    ]
