# Generated by Django 2.1.5 on 2019-03-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190306_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree_detail',
            old_name='timetable_1_year',
            new_name='notice',
        ),
        migrations.RemoveField(
            model_name='degree_detail',
            name='timetable_2_year',
        ),
        migrations.RemoveField(
            model_name='degree_detail',
            name='timetable_3_year',
        ),
        migrations.RemoveField(
            model_name='degree_detail',
            name='timetable_4_year',
        ),
        migrations.AddField(
            model_name='degree_detail',
            name='image',
            field=models.ImageField(default=0, upload_to='notice/'),
            preserve_default=False,
        ),
    ]
