# Generated by Django 2.1.5 on 2019-04-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_degree_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree_detail',
            name='notice',
            field=models.TextField(null=True),
        ),
    ]
