# Generated by Django 2.2 on 2019-05-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190403_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree_detail',
            name='notice',
        ),
    ]
