# Generated by Django 2.2 on 2019-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diploma_facultys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='media/teachers_img/')),
                ('Designation', models.CharField(max_length=400)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
