# Generated by Django 2.1.5 on 2019-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=400)),
                ('Qualification', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
    ]
