# Generated by Django 2.1.5 on 2019-02-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aside', '0002_auto_20190207_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultys',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/teachers_img/'),
        ),
    ]
