# Generated by Django 2.1.5 on 2019-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iert_news", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(default="def.png", upload_to="media/"),
        )
    ]
