# Generated by Django 2.1.5 on 2019-02-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iert_news", "0004_auto_20190211_1631")]

    operations = [migrations.RenameModel(old_name="news", new_name="new")]
