# Generated by Django 2.1.5 on 2019-03-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iert_news", "0018_new_no_of_comment")]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="no_of_comment",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        )
    ]
