# Generated by Django 2.1.5 on 2019-03-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("iert_news", "0019_auto_20190302_2134")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="iert_news.Comment",
            ),
        )
    ]
